when:
  event: [push, manual, deployment]
  branch: main

steps:
  frontend-build:
    image: node:20
    commands:
      - npm ci
      - npx prisma generate
      - npm run build -- --mode production
    when:
      path:
        include: [ 'src/**', 'public/**', 'vite.config.*', 'package.json', 'index.html' ]

  frontend-deploy:
    image: alpine:3.20
    commands:
      - apk add --no-cache rsync
      - rsync -a --delete dist/ /www/todo-matrix/app/
    volumes:
      - /Users/leon/www:/www
    when:
      status: success
      path:
        include: [ 'src/**', 'public/**', 'vite.config.*', 'package.json', 'index.html' ]
